services:
  api:
    container_name: ptitpote-api
    restart: always
    build:
      context: .
      dockerfile: docker/ptitpote/Dockerfile
      target: api
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ${PWD}/logs:/app/logs
  gateway:
    container_name: ptitpote-gateway
    restart: always
    build:
      context: .
      dockerfile: docker/ptitpote/Dockerfile
      target: gateway
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ${PWD}/logs:/app/logs
  database:
    image: mariadb:12.0.2-noble
    container_name: ptitpote-database
    env_file:
      - .env
    restart: always
    volumes:
      - ./docker/database/dumps/sql:/docker-entrypoint-initdb.d:ro
      - ./docker/database/bin:/database/bin:ro
      - ./docker/database/dumps://database/dumps:rw
      - mysqldbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 20
  localtunnel:
    container_name: ptitpote-lt
    restart: always
    build:
      context: .
      dockerfile: docker/localtunnel/Dockerfile
    command: --local-host api --port $APP_PORT --subdomain $LOCALTUNNEL_SUBDOMAIN
    env_file:
      - .env
    links:
      - api
    depends_on:
      - api

volumes:
  mysqldbdata:
