name: Quality Gate
on: [push]

jobs:
  QA:
    name: Apply Quality Gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Prepare ci env
        run: cp .env.sample .env
      - name: Build using Docker
        run: make ci
      - name: Execute tests in the running services
        run: make test
      - name: Lint
        run: make lint
